version: "3.9"

services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/auth-service.dockerfile
    container_name: auth-service
    restart: always
    ports:
      - "4000:4000"
    deploy:
      mode: replicated
      replicas: 1

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/gateway-service.dockerfile
    container_name: gateway-service
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    build:
      context: .
      dockerfile: logger-service/logger-service.dockerfile
    container_name: logger-service
    restart: always
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisDB:/data

networks:
  my-network:
    driver: bridge

volumes:
  redisDB:
